### ISSUE TITLE
Device Icons are missing from some Icon Themes

### ISSUE THREAD

**Issue by Queuecumber** [andyholmes/gnome-shell-extension-mconnect#7]
Not sure what I'm doing wrong here because I've heard reports of this working on 17.04

When I install the extension, I see a little phone icon on my main menu (top left). Opening the main menu now has a "Mobile Devices" section that when expanded only has "Mobile Settings". When I click that I can get to the mconnect extension settings and from there to the kde-connect GUI. That lists my phone as visible and pairable. I can also see and pair with the laptop from my phone.

However, my understanding is that there should be another phone icon in my top bar that lets me take actions with the phone, like initiating pairing outside of the kde-connect GUI, sending texts, viewing battery etc. I never see this other menu no matter who initiates pairing or in any other circumstance I could think to test (including disabling other extensions that mess with that top bar)

If I pair from my phone, I get a popup through gnome-shell to confirm it (I assume this is from the extension so that is working), and I get the following output in the debug log:

```
[mconnect@andyholmes.github.io]: DEBUG: extension.DeviceMenu._batteryChanged(false,-1)
[mconnect@andyholmes.github.io]: DEBUG: extension.DeviceMenu._pluginsChanged()
[mconnect@andyholmes.github.io]: DEBUG: extension.DeviceMenu._stateChanged(/modules/kdeconnect/devices/50f90ebdc0f0a10c)
[mconnect@andyholmes.github.io]: DEBUG: extension.DeviceMenu._pluginsChanged()
[mconnect@andyholmes.github.io]: DEBUG: extension.DeviceIndicator._sync()
[mconnect@andyholmes.github.io]: DEBUG: extension.DeviceMenu._stateChanged(/modules/kdeconnect/devices/50f90ebdc0f0a10c)
[mconnect@andyholmes.github.io]: DEBUG: extension.DeviceMenu._pluginsChanged()
[mconnect@andyholmes.github.io]: DEBUG: extension.DeviceMenu._batteryChanged(false,-1)
[mconnect@andyholmes.github.io]: DEBUG: extension.DeviceIndicator._sync()
[mconnect@andyholmes.github.io]: DEBUG: extension.DeviceMenu._batteryChanged(false,37)
```

Nothing that would obviously indicate an error and this is the only output in the debug log from the mconnect extension. I have tried installing the V2 zip file from the releases page and compiling from master using meson. 

I must be missing something so if you know what it is please let me know, also let me know what additional information I can provide. My `gnome-shell --version` currently reports 3.24.2

**Comment by Queuecumber** [comment]
And of course right as I post this I notice that the menu is there... but with an invisible icon (I noticed it when the spacing seemed off while activating a few more extensions). I'll leave this open in case the icon need fixing or something. Maybe this is related to my icon theme?

**Comment by andyholmes** [comment]
Ah, I was worried about that. I believe the icons I've been using are not available in some icon themes. I'll move to include icons with the extension itself. Thanks for the report, and the update.

**Comment by Queuecumber** [comment]
@andyholmes Weird thing is I see the icon in my main menu (the thing on the top right) but I don't see it in the main device menu that gets added when the phone is connected.

Also I'm testing the SMS interface now and that seems just shows a blank window, though I'm currently having some issues with GOA for my google account so it could be related.

**Comment by Queuecumber** [comment]
Coincidentally, I just got a text (which rarely happens) and I did get a notification through gnome-shell. SMS  GUI is still blank though (just a blank window with the title "MConnect") and my google account in GOA is fixed. Nothing suspicious in the debug log.

**Comment by andyholmes** [comment]
@Queuecumber I've just pushed a commit that should fix some issues with the SMS App.

Be aware that two way conversations aren't actually implemented yet, and might not be possible. I have plans to try and catch incoming Notifications and add them to the window if they match the outgoing contacts name/number to fake such a thing, but KDE Connect only supports sending SMS in the telephony plugin, not actually receiving them.

**Comment by andyholmes** [comment]
New release v3 uploaded, which should fix some of the SMS app problems, but not the missing icons, yet.

**Comment by andyholmes** [comment]
@Queuecumber Could tell me what Icon theme you experience this problem with? A look through my system shows that Adwaita should have all the necessary icons.

**Comment by Queuecumber** [comment]
In order:

That sounds like a major usability limitation for kde connect, SMS is pretty hard to use without a conversation-like interface, maybe I'll drop by their repo and ask about it

I pulled down master and did a clean rebuild, disabled mconnect, restarted my session, and reenabled and I still have a blank window for SMS. Also it seems like I need to press the SMS button in the device menu twice to get the window to pop up, not sure if thats related. 

So this is why I think something else weird is going on,  I can actually reset my GTK+ theme to Adwaita, my cursor theme to Adwaita, and my Shell theme to default, and restart my session andn I still dont see that icon. In fact now that I'm looking at it, in Adwaita icon theme, I lose the icon that was on the main menu as well. My normal icon theme is Arc, which shows the little phone icon on the main menu

**Comment by andyholmes** [comment]
Also in order:

I agree, in the KDE Connect repository there is [a code comment](https://github.com/KDE/kdeconnect-kde/blob/5f0173f4699d120a065e9cd7ce72d4a4860a5bc4/plugins/telephony/telephonyplugin.cpp#L49) which indicates that KDE Connect should try to offer telepathy the chance to take over, but although Gnome Shell includes it's own telepathy client I've never been able to get it to work.

Unfortunately sms.js is spawned as it's own process which makes debugging a little more difficult than usual. To get some useful debugging information you'll have to open a terminal and:

    cd ~/.local/share/gnome-shell/extensions/mconnect@andyholmes.github.io
    # list devices "<device-name>: <device-id>"
    gjs share.js -l
    gjs sms.js --device=<device-id>

I regards to the icons I'm quite puzzled, I'll download the Arc theme to see if that's in any way related.

**Comment by andyholmes** [comment]
@Queuecumber Since the icon I use for the System Indicator/User Menu "smartphone-symbolic" is not in the default theme,  I've changed it to "phone-apple-iphone-symbolic". In Numix this is the same icon anyways, while "phone-symbolic" is horrendous/small, and "smartphone-connected" doesn't do well in menus with lighter backgrounds and could cause confusion.

In regards to Arc and device icons, Arc claims to fall back to Moka, Adwaita, gnome and hicolor in that order, and my test show it does. I don't believe the original author is updating that theme anymore, so you may want to find a new favourite and/or check "index.theme" in the theme's root directory to set some new fallback's.

**Comment by tony5** [comment]
I am using version 5 and I am missing an icon.
it seems the phone icon should be moved to the missing location in the image I have attached.

I don't think having two icons would be necessary.

![screenshot](https://user-images.githubusercontent.com/9308991/29212243-754f2624-7e6b-11e7-84bf-72d9fccba6b3.png)

**Comment by andyholmes** [comment]
This is becoming quite a head scratcher. That looks like Adwaita icon theme, so the icon should be visible. Could you do me a favour and run `locate smartphone-connected` in a terminal to see if the icon is not present for some reason? I'm getting the feeling these icons have been patched in by some distros; which are you using?

In regards to having two icons, the "system indicator" icon is there to be consistent with Gnome Shell indicating that a particular service is active, such as Location Service in your screenshot, while the individual icons will differ depending on the device type (currently smartphone, tablet or laptop). I intended to make the icon visibility dynamic based on whether KDE Connect/MConnect was running, but forgot until now.

**Comment by tony5** [comment]
I don't have that icon. I will look into that later today.

**Comment by Queuecumber** [comment]
@andyholmes 

```
ㅌgjs share.js -l                                                                        ~/Code/gnome-shell-extension-mconnect/build/mconnect@andyholmes.github.io (master ⚡) mehrlich@lilith
pixel: 50f90ebdc0f0a10c
ㅌgjs sms.js --device=50f90ebdc0f0a10c                                                   ~/Code/gnome-shell-extension-mconnect/build/mconnect@andyholmes.github.io (master ⚡) mehrlich@lilith

(MConnect:4815): Gjs-WARNING **: JS ERROR: TypeError: phoneNumber.uri is null
ContactCompletion<._populate@sms.js:248:21
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
ContactCompletion<._init@sms.js:227:17
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
ContactEntry<._init@sms.js:339:25
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
ApplicationWindow<._init@sms.js:410:29
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
Application<.vfunc_activate@sms.js:661:33
wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
@sms.js:684:2
```
In addition to that it looks like I am periodically hit with [this bug](https://bugzilla.redhat.com/show_bug.cgi?id=1340203) in gnome. 

`locate smartphone-connected` gives back nothing for me, looks like I don't have that icon either

**Comment by Queuecumber** [comment]
Ok so my SMS window now seems to be functional, however, and this is probably a nice-to-have stretch goal, some of my contact names are not in english (e.g. not making use of latin characters) and I cant find them in search. I can find them if I start typing in their phone number though.

Additionally after pressing the SMS button it takes appx 5.5s for the window to open up (which is why I thought I needed to press it twice to get it to show). Maybe its indexing contacts before showing the window or something?

**Comment by andyholmes** [comment]
@Queuecumber In regards to missing icons, I'm looking into that now. There's a clean option with GResource files that's quite confusing and rather poorly documented, and an ugly option with large blocks of raw SVG pasted into the source code. News to come.

In regards to localised names in the SMS app, I'm not sure if that's because of being sorted/matched via Javascript or if it's a Google/GData issue or something else. I'd advise opening a new issue and I'll consider that a medium priority and get to it once things settle down a bit, since localisation is a goal.

In regards to loading time of the SMS app, I'm definitely aware of it. There is an asynchronous approach retrieving contacts, but I believe there's bug (possibly in the GData bindings) preventing it from working. At one point I tried native Javascript methods for threading/async but the version of GJS underneath Gnome Shell 3.24.x doesn't have the newer async/promise/threading stuff. I considered caching contacts locally, but that could be a security concern and the contacts wouldn't necessarily be up to date. Another option might be to skip GData and manually use Google People API via SOAP, but sms.js is already almost 100 lines longer than extension.js. Still, you could open an issue if you like, but ~5s makes it low priority for me right now.

**Comment by tony5** [comment]
@Queuecumber @andyholmes 
it looks like a reinstall of adwaita-icon-theme-full (3.24.0-0ubuntu1) fixes the issue.
thanks for making this extension!!!

**Comment by andyholmes** [comment]
@tony5 good find. If this works for @Queuecumber as well I'll close.

**Comment by Queuecumber** [comment]
Sorry for the late reply, yes the icon now shows after pulling latest code

**Comment by andyholmes** [comment]
Good to know, it would difficult to test without uninstalling all my icon themes ;) Apparently github auto-closes bugs if you mention them in a commit.
